<?php
/**
 * @file
 * Code for the Svendborg search feature.
 */

include_once 'svendborg_search.features.inc';

/**
 * Implements hook_form_alter()
 * does some visual modifications to the form
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function svendborg_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && ($form['#id'] == 'views-exposed-form-svendborg-elastic-search-panel-pane-menu' || $form['#id'] == 'views-exposed-form-svendborg-elastic-search-panel-pane-frontpage')) {
    $form['search_api_views_fulltext']['#theme_wrappers'] = array('bootstrap_search_form_wrapper');
    $form['search_api_views_fulltext']['#attributes']['placeholder'] = t('Search');
    $form['search_api_views_fulltext']['#attributes']['title'] = t('Enter the terms you wish to search for.');
    $form['submit']['#access'] = FALSE;
  }
}
