<?php
/**
 * @file
 * Code for the Svendborg search feature.
 */

include_once 'svendborg_search.features.inc';

/**
 * Implements hook_form_alter()
 * does some visual modifications to the form
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function svendborg_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && ($form['#id'] == 'views-exposed-form-svendborg-elastic-search-panel-pane-menu' || $form['#id'] == 'views-exposed-form-svendborg-elastic-search-panel-pane-frontpage')) {
    $form['search_api_views_fulltext']['#theme_wrappers'] = array('bootstrap_search_form_wrapper');
    $form['search_api_views_fulltext']['#attributes']['placeholder'] = t('Search');
    $form['search_api_views_fulltext']['#attributes']['title'] = t('Enter the terms you wish to search for.');
    $form['submit']['#access'] = FALSE;
  }
}

/**
 * Implements hook_file_insert()
 * adds node of type os2search_dokument per each uploaded PDF file, so that the files are being indexed
 * ignores file with source = 'submitted_file'
 *
 * @param $file
 */
function svendborg_search_file_insert($file) {
  if ($file->fid && $file->filemime == 'application/pdf' && $file->source != 'submitted_file') {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'os2search_dokument')
      ->propertyCondition('status', NODE_PUBLISHED)
      ->fieldCondition('field_os2search_file_ref', 'fid', $file->fid);
    $result = $query->execute();

    if (isset($result['node'])) {
      $nid = reset(array_keys($result['node']));
      $document_node = node_load($nid);
    } else {
      global $user;

      $document_node = new stdClass();
      $document_node->title = $file->filename;
      $document_node->type = 'os2search_dokument';
      node_object_prepare($document_node);
      $document_node->language = LANGUAGE_NONE;
      $document_node->uid = $user->uid;
      $document_node->status = 1;
      $document_node->promote = 0;
      $document_node->comment = 0;
    }

    $file->display = 1;
    $document_node->field_os2search_file_ref['und'][0] = (array) $file;

    node_submit($document_node);
    node_save($document_node);
  }
}

/**
 * Implements hook_file_delete()
 * when the file is deleted, the related node of type os2search_dokument is deleted as well.
 *
 * @param $file
 */
function svendborg_search_file_delete($file) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'os2search_dokument')
    ->fieldCondition('field_os2search_file_ref', 'fid', $file->fid);
  $result = $query->execute();

  if (isset($result['node'])) {
    $nid = reset(array_keys($result['node']));
    node_delete($nid);
  }
}

/**
 * Implements hook_node_update().
 *
 * Published or unpublished os2search_document nodes if there is no more node with the same status,
 * referencing the same file as os2search_document node.
 */
function svendborg_search_node_update($node) {
  $new_node_status = $node->status;

  if ($node->type !== 'os2search_dokument') {
    $node_fields = field_info_instances('node', $node->type);
    $file_fields = field_read_fields(array('type' => 'file'));
    $node_file_fields = array_intersect_key($node_fields, $file_fields);

    foreach ($node_file_fields as $field_name => $node_file_field) {
      $items = field_get_items('node', $node, $field_name);
      foreach ($items as $item) {
        $file = file_load($item['fid']);
        if ($file->filemime === 'application/pdf') {
          $usages = file_usage_list($file);
          $nids = $usages['file']['node'];

          // Unsetting current node nid.
          unset($nids[$node->nid]);

          if (!empty($nids)) {
            $usage_nodes = node_load_multiple(array_keys($nids));

            $update_document_nodes = TRUE;

            // If the new status is unpublished, check that the rest of the nodes referencing same file are also unpublished.
            if ($new_node_status == NODE_NOT_PUBLISHED) {
              foreach ($usage_nodes as $usage_node) {
                if ($usage_node->type !== 'os2search_dokument' && $usage_node->status == NODE_PUBLISHED) {
                  $update_document_nodes = FALSE;
                }
              }
            }

            // If the flag is unchanged, it means that either we only have os2search_dokument,
            // or new node status is PUBLISHED,
            // or the rest nodes referring file have the same publish status.

            // Updating os2search_dokument nodes.
            if ($update_document_nodes) {
              foreach ($usage_nodes as $usage_node) {
                if ($usage_node->type === 'os2search_dokument' && $usage_node->status != $new_node_status) {
                  $usage_node->status = $new_node_status;
                  node_save($usage_node);
                }
              }
            }
          }
        }
      }
    }
  }
}
