<?php

/**
 * @file
 * svendborg_os2web_contentpage.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function svendborg_os2web_contentpage_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'node-os2web_base_contentpage-field_os2web_base_field_fil_link'.
  $field_instances['node-os2web_base_contentpage-field_os2web_base_field_fil_link'] = array(
    'bundle' => 'os2web_base_contentpage',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'file',
        'settings' => array(),
        'type' => 'file_default',
        'weight' => 26,
      ),
      'includeable' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'spotbox' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_os2web_base_field_fil_link',
    'label' => 'Link til file',
    'required' => 0,
    'settings' => array(
      'description_field' => 1,
      'epsacrop' => array(
        'styles' => array(
          'os2web_spotbox_image' => 0,
          'svendborg_content_image' => 0,
          'svendborg_spotbox' => 0,
        ),
      ),
      'file_directory' => '',
      'file_extensions' => 'txt doc docx xls xlsx pdf',
      'max_filesize' => '',
      'user_register_form' => FALSE,
      'wysiwyg_insert' => 0,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'media',
      'settings' => array(
        'allowed_schemes' => array(
          'oembed' => 0,
          'private' => 0,
          'public' => 'public',
          'ustream' => 0,
          'youtube' => 0,
        ),
        'allowed_types' => array(
          'application' => 0,
          'audio' => 0,
          'document' => 'document',
          'image' => 'image',
          'video' => 0,
        ),
        'browser_plugins' => array(
          'media_browser_plus--media_browser_my_files' => 0,
          'media_browser_plus--media_browser_thumbnails' => 0,
          'media_default--media_browser_1' => 0,
          'media_default--media_browser_my_files' => 0,
          'media_internet' => 0,
          'upload' => 0,
        ),
      ),
      'type' => 'media_generic',
      'weight' => 47,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Link til file');

  return $field_instances;
}
