<?php

/*
 * Implements hook_mail_alter().
 */
function webform_alter_headers_mail_alter(&$message) {
	if (isset($message['headers']['Reply-To'])) {
		$message['headers']['From'] = $message['headers']['Reply-To'];
		$message['headers']['Sender'] = $message['headers']['Reply-To'];
		$message['headers']['Errors-To'] = $message['headers']['Reply-To'];
		$message['headers']['Return-Path'] = $message['headers']['Reply-To'];
	}
}
